backend:
  name: git-gateway
  branch: netlify-cms

media_folder: /src/pages/images

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "src/pages/images"
    public_folder: ""
    path: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "template", widget: "hidden", default: "post-template"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "FeatureImage", name: "feature-image", widget: "image" }
      - { label: "ImageAltText", name: "alt-text", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }